server:
  port: 8181
  
logging:
  level.: INFO
  
security:
  user:
    password: abc

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/userdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: 
      ddl-auto: false 

flyway:
  baseline-on-migrate: true
  
    